version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      # run 'npm install' using versions in package-lock.json
      - npm ci
  build:
    commands:
      - npm run build
artifacts:
  files:
    - start-service.sh
    - stop-service.sh
    - server.js
    - expressServer.js
    - package.json
    - appspec.yml
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'expressApp/**/*'